github:
    auth_token: ${GITHUB_TOKEN}
    request_timeout: 10
search:
    default_term: "Dependency Injector"
    default_limit: 10
webapp:
    port: 8080
    host: "0.0.0.0"
    templates_dir: "githubnavigator/website/templates/"
